<a href="https://colab.research.google.com/github/ZahirulNiloyCodes/CSE_422_Project/blob/main/Cse422_Project_Group7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# @title Data Pre Processing
dataset=pd.read_csv('7.csv')
dataset=dataset.drop(columns=['Student ID'])
dataset=dataset.dropna(subset=['Diabetes',"Smoking"])
dataset=dataset.dropna(subset=["Gender"])
#print(dataset)
x_data=dataset.iloc[:,:-2].to_numpy()
y_1=dataset.iloc[:,-2].to_numpy()
y_2=dataset.iloc[:,-1].to_numpy()
#print(y_1)
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[4])],remainder='passthrough')
le=LabelEncoder()
x_data[:,1]=le.fit_transform(x_data[:,1])
print(x_data)
x_data=np.array(transformer.fit_transform(x_data))
y_1=le.fit_transform(y_1)
y_2=le.fit_transform(y_2)
#print(x_data)
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
#imputer.fit(x_data[:,3:])
#x_data[:,3:]=imputer.transform(x_data[:,3:])
#print(x_data[:10,:])

[[nan 1 152.06915679450026 ... 93.0 104.0 163.0]
 [32.0 0 182.5376635180374 ... 76.0 130.0 216.0]
 [30.0 1 182.1128671625788 ... 99.0 112.0 141.0]
 ...
 [24.0 1 176.50325952058026 ... 65.0 121.0 130.0]
 [29.0 0 163.91767529286994 ... 62.0 125.0 198.0]
 [30.0 0 156.44694436241386 ... 61.0 106.0 225.0]]


In [ ]:
# @title Splitting Data
from sklearn.model_selection import train_test_split

